baseURL = "https://www.henriksommerfeld.se/"
languageCode = "en-gb"
title = "Henrik Sommerfeld's blog"
canonifyURLs = false
relativeURLs = false
buildDrafts = false
paginate = 5
pygmentsuseclasses = true
pygmentsstyle = "monokai"
preserveTaxonomyNames = true
googleAnalytics = "UA-36834923-2"
disqusShortname = "henrik-sommerfeld"

[permalinks]
    article = "/:title/"